aliases:
  branches:
    only:
      - master


version: 2
jobs:
  deploy-website:
    docker:
      # 在此处指定所需的版本

      - image: circleci/node:8.11.1

    steps:

      - checkout
      - run:
          name: 部署到GitHub页面
          command: |
            git config --global user.email "2504919830@qq.com"
            git config --global user.name "SanLi"
            echo "machine github.com login 2504919830@qq.com password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=2504919830@qq.com yarn run publish-gh-pages